name: 'Set approved label and automerge'
description: 'Set approved label and automerge'

inputs:
   GITHUB_TOKEN:
     description: 'Github token'
     required: false
   repo:
     description: 'Repository'
     required: false
   dir:
      description: 'Directory'
      required: false
   base_branch:
      description: 'Github token'
      required: false
      default: 'develop'
  days_old:
      description: 'Days old to delete'
      required: false
      default: '120'

runs:
   using: 'docker'
   image: 'Dockerfile'
   args:
      - ${{ inputs.GITHUB_TOKEN }}
      - ${{ inputs.repo}}
      - ${{ inputs.dir }}
      - ${{ inputs.base_branch }}
      - ${{ inputs.days_old }}