name: 'Delete old files from a folder'
description: 'Delete files that were created than x days ago'

inputs:
   GITHUB_TOKEN:
     description: 'Github token'
     required: true
   dir:
      description: 'Directory'
      required: true
   base_branch:
      description: 'Base branch to pull request'
      required: false
      default: 'develop'
   days_old:
      description: 'Days old to delete'
      required: false
      default: '120'
   pr_title:
     description: 'Pull request title'
     required: false
     default: 'Delete old files'
runs:
   using: 'docker'
   image: 'Dockerfile'
   args:
      - ${{ inputs.GITHUB_TOKEN }}
      - ${{ inputs.dir }}
      - ${{ inputs.base_branch }}
      - ${{ inputs.days_old }}
      - ${{ inputs.pr_title }}

branding:
  icon: 'tag'
  color: 'green'
